### ISSUE TITLE
Curses doesn't install for Python 3.6.3 on Raspberry pi

### ISSUE THREAD

**Issue by Menox10** [mcardillo55/cbpro-trader#9]
Python 3.6.3 (default, Jan  8 2019, 21:35:12)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import curses
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

On Python 2.7 it works but then I can not install Ta-Lib. For Python 3.6 it is curses that is hard to find and not possible to install. Could you maybe make more use of general python modules. The Ta-Lib is needed I think but maybe there is an alternative for curses.

Can I modify the code to run without curses?

**Comment by Menox10** [comment]
I could solve this issue by reverting back to python 3.4. The module curses default in this version.

**Comment by mcardillo55** [comment]
I'm running Python 3.5.3 on my RPi and it finds curses just fine. Is this perhaps local to your installation? It looks like it actually FINDS curses, but has some trouble finding the actual internal library files. Regardless, it sounds like you found a workaround. You could also change `frontend=debug` in the config file for just plain text output. I hope to start work on a web frontend soon actually too. I'm gonna go ahead and close the issue though.
